# permissions for end users to edit brokes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubebuilder-rocketmq
    app.kubernetes.io/managed-by: kustomize
  name: broke-editor-role
rules:
- apiGroups:
  - apps.hyj.cn
  resources:
  - brokes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.hyj.cn
  resources:
  - brokes/status
  verbs:
  - get
