---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.hyj.cn
  resources:
  - brokes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.hyj.cn
  resources:
  - brokes/finalizers
  verbs:
  - update
- apiGroups:
  - apps.hyj.cn
  resources:
  - brokes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps.hyj.cn
  resources:
  - nameservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.hyj.cn
  resources:
  - nameservices/finalizers
  verbs:
  - update
- apiGroups:
  - apps.hyj.cn
  resources:
  - nameservices/status
  verbs:
  - get
  - patch
  - update
